# Generated by Django 5.2 on 2025-05-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelada',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='pelada',
            name='local',
        ),
        migrations.AddField(
            model_name='pelada',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
