# Generated by Django 5.2 on 2025-05-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelada', '0002_remove_pelada_hora_remove_pelada_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepelada',
            name='media',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pelada',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
