# Generated by Django 5.2 on 2025-05-30 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelada', '0003_participantepelada_media_pelada_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelada',
            name='dia',
        ),
    ]
