# Generated by Django 5.2 on 2025-06-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelada', '0004_remove_pelada_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantepelada',
            name='media',
        ),
        migrations.AddField(
            model_name='participantepelada',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
