# Generated by Django 5.2 on 2025-06-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelada', '0005_remove_participantepelada_media_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantepelada',
            unique_together=set(),
        ),
    ]
